### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by zxhycxq** [XZiar/ZhiHuExt#3]
我用两种方式下载安装，但是都没法正常加载插件（360浏览器和chrome浏览器，已经开启开发者模式）。

ps：没有发布到chrome应用商店吗？

**Comment by XZiar** [comment]
没发布到chrome商店。
有报错的提示吗？浏览器版本如何？
如果是直接clone这个项目的话，得选里面的ZhiHuExt文件夹。crx安装应该没问题才对……

**Comment by zxhycxq** [comment]
![crx](https://user-images.githubusercontent.com/11674203/37562548-6fa73ed6-2aa6-11e8-893d-495de1542387.png)
![crx2](https://user-images.githubusercontent.com/11674203/37562553-a0fa9500-2aa6-11e8-9353-623c0751453d.png)
![crx3](https://user-images.githubusercontent.com/11674203/37562566-fd166364-2aa6-11e8-9829-cbf83cb44566.png)

图1 是360浏览器，另外两个是chrome浏览器下两种加载方式的结果。我下载的最新版的。

**Comment by XZiar** [comment]
我检查了一下我这边是完全没有问题的，我的chrome版本是64和65，manifest里写要求最低版本是58，不知道是不是浏览器版本的问题？
https://www.v2ex.com/t/413130
这里提到国产浏览器不兼容新版的打包格式。

另外手动安装需要到chrome://extensions/页面，直接拖进浏览器似乎是会提示“无法添加……”

**Comment by zxhycxq** [comment]
@XZiar  我用chrome金丝雀版可以了，多谢了
