### ISSUE TITLE
chrome最新版修改组策略后还是不能用非商店插件

### ISSUE THREAD

**Issue by jiahe224** [XZiar/ZhiHuExt#4]
你们怎么解决的呢？

**Comment by XZiar** [comment]
把插件拖进扩展程序页面，而不是直接拖进chrome。

**Comment by jiahe224** [comment]
我就是在“管理扩展程序”界面打开开发者模式，再把插件拖进去，安装后只要联网，立马会提示“该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。”组策略中已经加入扩展白名单，经测验chrome62版可以用组策略安装，后面的都不行

**Comment by jiahe224** [comment]
刚又看了看，组策略两个配置里都有模板，得加在计算机配置里
